# Generated by Django 5.2.12 on 2026-03-16 12:19

import bn.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre de la Partida', max_length=200)),
                ('cant_jugadores', models.PositiveIntegerField(default=2)),
                ('cant_acorazados', models.PositiveIntegerField(default=1)),
                ('cant_patrullas', models.PositiveIntegerField(default=1)),
                ('cant_portaaviones', models.PositiveIntegerField(default=1)),
                ('cant_submarinos', models.PositiveIntegerField(default=1)),
                ('cant_fragatas', models.PositiveIntegerField(default=1)),
                ('cant_turnos_totales', models.PositiveIntegerField(default=0)),
                ('cant_turnos_de_la_ronda', models.PositiveIntegerField(default=0)),
                ('ancho_tablero', models.PositiveIntegerField(default=9)),
                ('numero_ronda_actual', models.PositiveIntegerField(default=0)),
                ('iniciada', models.BooleanField(default=False)),
                ('terminada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveIntegerField(default=0)),
                ('es_su_turno', models.BooleanField(default=False)),
                ('ya_ataco', models.BooleanField(default=False)),
                ('ubicaciones_confirmadas', models.BooleanField(default=False)),
                ('derrotado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_contra_mi', to='bn.jugador')),
                ('desde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar', to='bn.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.PositiveIntegerField()),
                ('cant_acorazados', models.PositiveIntegerField()),
                ('cant_patrullas', models.PositiveIntegerField()),
                ('cant_portaaviones', models.PositiveIntegerField()),
                ('cant_submarinos', models.PositiveIntegerField()),
                ('cant_fragatas', models.PositiveIntegerField()),
                ('hay_escudo', models.BooleanField(default=False)),
                ('posicion_escudo', bn.fields.TupleField(blank=True, null=True)),
                ('ronda_ultimo_escudo', models.IntegerField(default=-4)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bn.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Submarino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal', models.BooleanField(default=True)),
                ('hundido', models.BooleanField(default=False)),
                ('puntos_tocados', bn.fields.ListField(blank=True, null=True)),
                ('esta_sumergido', models.BooleanField(default=False)),
                ('veces_sumergimiento', models.PositiveIntegerField(default=0)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.tablero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portaaviones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal', models.BooleanField(default=True)),
                ('hundido', models.BooleanField(default=False)),
                ('puntos_tocados', bn.fields.ListField(blank=True, null=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.tablero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patrulla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal', models.BooleanField(default=True)),
                ('hundido', models.BooleanField(default=False)),
                ('puntos_tocados', bn.fields.ListField(blank=True, null=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.tablero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fragata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal', models.BooleanField(default=True)),
                ('hundido', models.BooleanField(default=False)),
                ('puntos_tocados', bn.fields.ListField(blank=True, null=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.tablero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acorazado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal', models.BooleanField(default=True)),
                ('hundido', models.BooleanField(default=False)),
                ('puntos_tocados', bn.fields.ListField(blank=True, null=True)),
                ('ronda_ultimo_ataque_potente', models.IntegerField(default=-3)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn.tablero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableroVisible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_atacados', bn.fields.ListField(blank=True, null=True)),
                ('tiros_agua', bn.fields.ListField(blank=True, null=True)),
                ('tiros_escudo', bn.fields.ListField(blank=True, null=True)),
                ('hay_radar', models.BooleanField(default=False)),
                ('posicion_radar', bn.fields.TupleField(blank=True, null=True)),
                ('turno_del_radar', models.IntegerField(blank=True, null=True)),
                ('jugador_atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_visibles', to='bn.jugador')),
                ('tablero_atacado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibles', to='bn.tablero')),
            ],
        ),
    ]
